### ISSUE TITLE
Failed to extract AppleMediaServices on iOS 14.4.1 and iPhone 6s

### ISSUE THREAD

**Issue by weizenberg** [arandomdev/DyldExtractor#12]
I'm trying to extract the AppleMediaServices framework, but it failed with the following error:

```
Extracting AppleMediaServices
18:23:31:183 StubConverter.py [WARNING ] : No symbol for: 0x18ad2d6e8
18:23:31:191 StubConverter.py [WARNING ] : No symbol for: 0x18ad324ac
18:23:31:198 StubConverter.py [WARNING ] : No symbol for: 0x18ad36b94
18:23:31:218 StubConverter.py [WARNING ] : No symbol for: 0x181fa53ac
Traceback (most recent call last):
  File "/Users/guyco/Documents/GitHub/DyldExtractor/extractor.py", line 146, in <module>
    extractImage(dyldFile, dyldFile.images[targetImageData[0]], args.output)
  File "/Users/guyco/Documents/GitHub/DyldExtractor/extractor.py", line 70, in extractImage
    Converter.StubConverter(machoFile, dyld).convert()
  File "/Users/guyco/Documents/GitHub/DyldExtractor/DyldExtractor/Converter/StubConverter.py", line 118, in convert
    self.fixCallsites()
  File "/Users/guyco/Documents/GitHub/DyldExtractor/DyldExtractor/Converter/StubConverter.py", line 463, in fixCallsites
    targetFunc = self.resolveTarget(target)
  File "/Users/guyco/Documents/GitHub/DyldExtractor/DyldExtractor/Converter/StubConverter.py", line 278, in resolveTarget
    nextAddr = self.stubTarget(currentAddr)
  File "/Users/guyco/Documents/GitHub/DyldExtractor/DyldExtractor/Converter/StubConverter.py", line 182, in stubTarget
    self.dyldFile.file.seek(stubFileOff)
OSError: [Errno 22] Invalid argument
```

1. iOS version: 14.4.1
2. DYLD target device: iPhone 6s
3. Terminal command: python3 extractor.py -f AppleMediaServices -o AppleMediaServices dyld_shared_cache_arm64

**Comment by arandomdev** [comment]
fixed with f28b04938f3d1dd0fc077e86bc2ffa4d6876b603. Thanks for the report!
