### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by HAHALOSAH** [arandomdev/DyldExtractor#35]
**Describe the bug**
A clear and concise description of what the bug is. Include the error message too.

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/gaming/.local/bin/dyldex", line 17, in <module>
    from DyldExtractor.extraction_context import ExtractionContext
  File "/home/gaming/.local/lib/python3.8/site-packages/DyldExtractor/extraction_context.py", line 4, in <module>
    from DyldExtractor.dyld.dyld_context import DyldContext
  File "/home/gaming/.local/lib/python3.8/site-packages/DyldExtractor/dyld/dyld_context.py", line 11, in <module>
    class DyldContext(object):
  File "/home/gaming/.local/lib/python3.8/site-packages/DyldExtractor/dyld/dyld_context.py", line 104, in DyldContext
    def addSubCaches(self, subCacheFileCtxs: list[FileContext]) -> None:
TypeError: 'type' object is not subscriptable

**To Reproduce**
1. iOS version 14.8
2. DYLD target device and identifier: iPhone 11 (iPhone12,1)
3. Terminal command to reproduce: dyldex -e SpringBoardHome.framework/SpringBoardHome dyld_shared_cache_arm64e

**Additional context**
Running on linux

**Comment by arandomdev** [comment]
This seems like a problem with your python installation instead of DyldExtractor, maybe try the solutions referenced here, https://stackoverflow.com/questions/56155627/requestsdependencywarning-urllib3-1-25-2-or-chardet-3-0-4-doesnt-match-a-s

**Comment by HAHALOSAH** [comment]
Traceback (most recent call last):
  File "/home/gaming/.local/bin/dyldex", line 17, in <module>
    from DyldExtractor.extraction_context import ExtractionContext
  File "/home/gaming/.local/lib/python3.8/site-packages/DyldExtractor/extraction_context.py", line 4, in <module>
    from DyldExtractor.dyld.dyld_context import DyldContext
  File "/home/gaming/.local/lib/python3.8/site-packages/DyldExtractor/dyld/dyld_context.py", line 11, in <module>
    class DyldContext(object):
  File "/home/gaming/.local/lib/python3.8/site-packages/DyldExtractor/dyld/dyld_context.py", line 104, in DyldContext
    def addSubCaches(self, subCacheFileCtxs: list[FileContext]) -> None:
TypeError: 'type' object is not subscriptable

Ran command "dyldex" without any arguments

**Comment by arandomdev** [comment]
try to uninstall it and then reinstall it with
`pip install git+https://github.com/arandomdev/DyldExtractor.git`
I may need to just push another package to pypi.

**Comment by arandomdev** [comment]
I assume that reinstalling the latest version solved your issue. I uploaded it to pypi so I'll close this issue.
