### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_x86_64h.1' 

### ISSUE THREAD

**Issue by torarnv** [arandomdev/DyldExtractor#49]
macOS 13.1

FileNotFoundError: [Errno 2] No such file or directory: '/System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_x86_64h.1'
"""

Fixed by changing to
```
# has 1-based index extension
subCachePath = mainCachePath.with_suffix(f".{i + 1:02}")
```

in dyld_context.py

**Comment by arandomdev** [comment]
I assumed that the cache would use the newer sub cache entry info if the `cacheType` was equal to 2 but that doesn't seem to be the case. Can you send me the first 4096 bytes of the main cache file? The following command should work, `dd count=4096 if=INPUT_FILE of=OUTPUT_FILE`.

Thanks.

**Comment by torarnv** [comment]
`dd count=4096 if=/System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_x86_64h of=/tmp/c
ache_header_x86_64h`

[cache_header_x86_64h.zip](https://github.com/arandomdev/DyldExtractor/files/10262186/cache_header_x86_64h.zip)

Thanks!

**Comment by torarnv** [comment]
Thanks!

I now get:
```
❯ /Users/torarne/Library/Python/3.9/bin/dyldex -e AppKit.framework/Versions/C/AppKit /System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_x86_64h
Extracting /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
Optimize Linkedit >> Copy Local Symbols :: [/]                                                                                                                                                                               Traceback (most recent call last):
  File "/Users/torarne/Library/Python/3.9/bin/dyldex", line 277, in <module>
    main()
  File "/Users/torarne/Library/Python/3.9/bin/dyldex", line 272, in main
    _extractImage(args.dyld_path, dyldCtx, imageMap[targetPaths[0]], outputPath)
  File "/Users/torarne/Library/Python/3.9/bin/dyldex", line 136, in _extractImage
    linkedit_optimizer.optimizeLinkedit(extractionCtx)
  File "/Users/torarne/Library/Python/3.9/lib/python/site-packages/DyldExtractor/converter/linkedit_optimizer.py", line 600, in optimizeLinkedit
    optimizer.copyLocalSymbols(newLinkedit)
  File "/Users/torarne/Library/Python/3.9/lib/python/site-packages/DyldExtractor/converter/linkedit_optimizer.py", line 270, in copyLocalSymbols
    if symbolsCache.header.localSymbolsOffset == 0:
AttributeError: 'NoneType' object has no attribute 'header'
```

**Comment by torarnv** [comment]
Looks like https://github.com/arandomdev/DyldExtractor/issues/45, so this can be closed

**Comment by arandomdev** [comment]
Ok, closing with 7a21e84357d1d8222732231b646978f14d60115d.
