### ISSUE TITLE
Will this work on dyld_shared_cache_x86_64 in Big Sur?

### ISSUE THREAD

**Issue by norey** [arandomdev/DyldExtractor#6]
I tried it with `-l` on `dyld_shared_cache_x86_64` and it listed everything fine. But when I tried to extract a module, I got this

```
% python3 extractor.py -f AudioToolboxCore dyld_shared_cache_x86_64
Extracting AudioToolboxCore
Traceback (most recent call last):
  File "/Users/user/tools/DyldExtractor/extractor.py", line 150, in <module>
    extractImage(dyldFile, dyldFile.images[targetImageData[0]], "binaries\\"+targetImageData[1])
  File "/Users/user/tools/DyldExtractor/extractor.py", line 58, in extractImage
    Converter.LinkeditConverter(machoFile, dyld).convert()
  File "/Users/user/tools/DyldExtractor/DyldExtractor/Converter/LinkeditConverter.py", line 28, in convert
    self.getLocalSymEntry()
  File "/Users/user/tools/DyldExtractor/DyldExtractor/Converter/LinkeditConverter.py", line 79, in getLocalSymEntry
    for entry in self.dyldFile.localSymbolInfo.entries:
AttributeError: 'NoneType' object has no attribute 'entries'
```

**Comment by arandomdev** [comment]
As of now, it does not support x86_64. while it may be a very long term goal, this project will focus mainly on arm.
