### ISSUE TITLE
iOS 7 dyld cache unable to extract Private.Framework binary

### ISSUE THREAD

**Issue by P5-2005** [arandomdev/DyldExtractor#7]
hello,
im trying to extract binary from ios 7, i can list all framework from the cache, but cannot extract anyone

./extractor.py  -f MobileActivation dyld_shared_cache_armv7           
Extracting MobileActivation
Traceback (most recent call last):
  File "./extractor.py", line 150, in <module>
    extractImage(dyldFile, dyldFile.images[targetImageData[0]], "binaries\\"+targetImageData[1])
  File "./extractor.py", line 54, in extractImage
    machoFile = MachO.MachoFile.parse(dyld.file, imageOff)
  File "/Users/p5/Downloads/DyldExtractor-master/DyldExtractor/MachO/MachoFile.py", line 67, in parse
    raise Exception("Unknown Loadcommand: " + LoadCommands(cmd).name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 668 is not a valid LoadCommands

**Comment by arandomdev** [comment]
Judging from the name of your cache, you seem to be using a 32bit version. This tool does not support this at all.

You would probably have a better chance by trying it with a 64bit version, sorry.

**Comment by P5-2005** [comment]
thanks, i will try with 64bit version

**Comment by P5-2005** [comment]
I tried with 64bits dyld for iOS 7, now I have another error about macho :

p5@P5s-MacBook-Pro DyldExtractor-master % python3 extractor.py -f MobileActivation dyld_shared_cache_arm64
Extracting MobileActivation
Traceback (most recent call last):
  File "/Users/p5/Downloads/DyldExtractor-master/extractor.py", line 150, in <module>
    extractImage(dyldFile, dyldFile.images[targetImageData[0]], "binaries\\"+targetImageData[1])
  File "/Users/p5/Downloads/DyldExtractor-master/extractor.py", line 54, in extractImage
    machoFile = MachO.MachoFile.parse(dyld.file, imageOff)
  File "/Users/p5/Downloads/DyldExtractor-master/DyldExtractor/MachO/MachoFile.py", line 67, in parse
    raise Exception("Unknown Loadcommand: " + LoadCommands(cmd).name)
Exception: Unknown Loadcommand: LC_VERSION_MIN_IPHONEOS
