### ISSUE TITLE
iOS 7- 64bits dyld cache unable to extract Private.Framework binary, dependencies ?

### ISSUE THREAD

**Issue by P5-2005** [arandomdev/DyldExtractor#8]
p5@P5s-MacBook-Pro DyldExtractor-master % python3 extractor.py -f MobileActivation dyld_shared_cache_arm64
Extracting MobileActivation
Traceback (most recent call last):
  File "/Users/p5/Downloads/DyldExtractor-master/extractor.py", line 150, in <module>
    extractImage(dyldFile, dyldFile.images[targetImageData[0]], "binaries\\"+targetImageData[1])
  File "/Users/p5/Downloads/DyldExtractor-master/extractor.py", line 54, in extractImage
    machoFile = MachO.MachoFile.parse(dyld.file, imageOff)
  File "/Users/p5/Downloads/DyldExtractor-master/DyldExtractor/MachO/MachoFile.py", line 67, in parse
    raise Exception("Unknown Loadcommand: " + LoadCommands(cmd).name)
Exception: Unknown Loadcommand: LC_VERSION_MIN_IPHONEOS

**Comment by arandomdev** [comment]
In order for my to properly fix this, what version of iOS are you using and what device is the cache for.

Also this tool has really only tested on iOS 13. So in the mean time, try that?

**Comment by P5-2005** [comment]
ios 7.1.2 for iphone 5s 64bits
