### ISSUE TITLE
Not working for arm64e on macOS Big Sur

### ISSUE THREAD

**Issue by aBradleyUno** [arandomdev/DyldExtractor#9]
**Describe the bug**

Crashes when trying to extract library on macOS targeting arm64e 

```
./extractor.py -f libxcselect.dylib -o ./libxcselect.dylib /System/Library/dyld/dyld_shared_cache_arm64e                                                                                 master
Extracting libxcselect.dylib
Traceback (most recent call last):
  File "/Users/lex/Developer/DyldExtractor/./extractor.py", line 146, in <module>
    extractImage(dyldFile, dyldFile.images[targetImageData[0]], args.output)
  File "/Users/lex/Developer/DyldExtractor/./extractor.py", line 58, in extractImage
    Converter.LinkeditConverter(machoFile, dyld).convert()
  File "/Users/lex/Developer/DyldExtractor/DyldExtractor/Converter/LinkeditConverter.py", line 30, in convert
    self.buildSymbolTable()
  File "/Users/lex/Developer/DyldExtractor/DyldExtractor/Converter/LinkeditConverter.py", line 174, in buildSymbolTable
    dysymtabCommand.nlocalsym = self.localSymEntry.nlistCount
AttributeError: 'LinkeditConverter' object has no attribute 'localSymEntry'
```

**To Reproduce**
ProductName:	macOS
ProductVersion:	11.0
BuildVersion:	20A5354i

**Additional context**
Maybe I'm doing something wrong?

**Comment by arandomdev** [comment]
I really should update the docs, but this only supports iOS caches, with the best results for disassembly being from arm64.
